from . import yuemei_fit
from . import agenda_agenda
from . import nkdh_line
from . import project_task
from . import purchase_order
from . import res_partner
from . import sale_order
from . import res_air_plan
from . import hotel_fit
